server:
    port: 9001
    tomcat:
        connection-timeout: 60000ms
file:
    path: //Users//odin//Downloads//file//

spring:
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 200MB
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/bigfileupload?characterEncoding=utf-8&useSSL=false
        username: root
        password: root

